version: '3.7'


services:
  clickhouse-server:
    image: antrea/clickhouse-server
    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '9009:9000'
    volumes:
      - ./db:/var/lib/clickhouse
    ulimits:
      nofile: 262144 